mybatis:
  type-aliases-package: life.majiang.community.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: @db.url@community?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: @db.user@
    password: @db.password@
    driver-class-name: @db.driver@

server:
  port: 8081



